### ISSUE TITLE
Window.object is null after using windowManager.createNew()

### ISSUE THREAD

**Issue by Bossehasse** [azain/electron-window-manager#24]
So this is my code:
```javascript
trayWindow = windowManager.createNew('tray', 'Tray', `${config.url}/tray.html`, null, {
    width: 1000,
    height: 600,
    frame: false,
    resizable: false,
    moveable: false,
    show: false,
    position: 'topLeft'
}, true)

console.log('trayWindow.object:', trayWindow.object) // trayWindow.object: null
```

Is this how it should be? If I do this:
```javascript
trayWindow.create()
console.log('trayWindow.object:', trayWindow.object) // trayWindow.object: BrowserWindow
```
everything is fine. Just curious if all is as it should be. Seems odd to me that `object` doesn't get set during `createNew()`.

**Comment by azain** [comment]
I see, the problem is within Window.create; it doesn't return the object that createNew should return. Will fix it, thanks.

**Comment by azain** [comment]
Fixed

**Comment by Bossehasse** [comment]
Just updated and the problem still persists. Looking into it, `createWindow()` returns a new `Window` instance, but during the initialization `create()` is never called. And so `object` is never set.
